CREATE SCHEMA IF NOT EXISTS cepdb;

USE cepdb;

CREATE TABLE IF NOT EXISTS ceps (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CEP VARCHAR(8) NOT NULL UNIQUE,
  UF VARCHAR(2) NOT NULL,
  cidade VARCHAR(30) NOT NULL,
  bairro VARCHAR(30) NOT NULL,
  logradouro VARCHAR(30) NOT NULL
);
